# Generated by Django 2.2 on 2020-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('employee_email', models.CharField(blank=True, max_length=200)),
                ('employee_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
